apiVersion: v2
name: bitcoin
version: 0.0.0
dependencies:
  - name: app-template
    alias: bitcoind
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
  - name: app-template
    alias: tor
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
  - name: app-template
    alias: electrs
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
