---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: actual-secrets
spec:
  itemPath: "vaults/Kubernetes/items/actual"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: actual-sync-secrets
spec:
  itemPath: "vaults/Kubernetes/items/actual-sync"
