---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: actual-sync
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 5
      activeDeadlineSeconds: 1200
      template:
        spec:
          containers:
            - name: actual-sync
              image: curlimages/curl:8.21.0
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - 'curl --fail --silent --show-error -X POST "http://actual-sync:8080/api/v1/sync"'
          restartPolicy: Never
