apiVersion: v2
name: kube-prometheus-stack
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 74.2.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: influxdb
    version: 4.12.5
    repository: https://helm.influxdata.com/
