apiVersion: v2
name: kube-prometheus-stack
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 48.3.1 # TODO https://github.com/prometheus-community/helm-charts/issues/3396
    repository: https://prometheus-community.github.io/helm-charts
