apiVersion: v2
name: onepassword
version: 0.0.0
dependencies:
  - name: connect
    version: 2.3.0
    repository: https://1password.github.io/connect-helm-charts
  - name: external-secrets
    version: 2.0.1
    repository: https://charts.external-secrets.io
