{
 "title": "K8up Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Duration Since Last Backup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - last_over_time(timestamp(changes(k8up_backup_restic_available_snapshots[1m]) > 0)[4w:30s])",
     "legendFormat": "{{` {{instance}} `}}"
    }
   ]
  },
  {
   "title": "Errors in Last Backup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (k8up_backup_restic_last_errors)",
     "legendFormat": "{{` {{instance}} `}}"
    }
   ]
  },
  {
   "title": "Available Snapshots",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(k8up_backup_restic_available_snapshots)",
     "legendFormat": " {{` {{instance}} `}} "
    }
   ]
  },
  {
   "title": "Number of Snapshots (wrong!)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (k8up_backup_restic_available_snapshots)",
     "legendFormat": "{{` {{instance}} `}}"
    }
   ]
  },
  {
   "title": "New Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "k8up_backup_restic_new_files_during_backup",
     "legendFormat": " {{` {{instance}} `}} "
    }
   ]
  },
  {
   "title": "New Directories",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "k8up_backup_restic_new_directories_during_backup",
     "legendFormat": " {{` {{instance}} `}} "
    }
   ]
  },
  {
   "title": "Changed Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "k8up_backup_restic_changed_files_during_backup",
     "legendFormat": " {{` {{instance}} `}} "
    }
   ]
  },
  {
   "title": "Changed Directories",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "k8up_backup_restic_changed_directories_during_backup",
     "legendFormat": " {{` {{instance}} `}} "
    }
   ]
  }
 ]
}