{
 "title": "TC4400",
 "description": "DOCSIS Cable Modem",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Receive SNR/MER Threshold Value",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tc4400_downstream_snr_threshold_db",
     "legendFormat": "{{ `{{channel}}` }}"
    }
   ]
  },
  {
   "title": "Downstream Channel Status",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(tc4400_downstream_center_frequency_hz) by (channel)"
    },
    {
     "expr": "avg(tc4400_downstream_locked) by (channel)"
    },
    {
     "expr": "avg(tc4400_downstream_bonded) by (channel)"
    },
    {
     "expr": "avg(tc4400_downstream_channel_type) by (channel,type)"
    },
    {
     "expr": "avg(tc4400_downstream_width_hz) by (channel)"
    },
    {
     "expr": "avg(tc4400_downstream_modulation) by (channel,modulation)"
    }
   ]
  },
  {
   "title": "Receive Level (dBmV)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tc4400_downstream_receive_level_dbmv",
     "legendFormat": "{{ `{{channel}}` }}"
    }
   ]
  },
  {
   "title": "Thresholds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive SNR/MER Threshold Value (QAM256)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "expr": "tc4400_downstream_snr_threshold_db and on(channel) tc4400_downstream_modulation{modulation=~\"QAM256\"}",
       "legendFormat": "{{ `{{channel}}` }}"
      }
     ]
    },
    {
     "title": "Receive SNR/MER Threshold Value (QAM64)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "expr": "tc4400_downstream_snr_threshold_db and on(channel) tc4400_downstream_modulation{modulation=~\"QAM64\"}",
       "legendFormat": "{{ `{{channel}}` }}"
      }
     ]
    },
    {
     "title": "Receive Level (dBmV) (QAM256)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "tc4400_downstream_receive_level_dbmv and on(channel) tc4400_downstream_modulation{modulation=~\"QAM256\"}",
       "legendFormat": "{{ `{{channel}}` }}"
      }
     ]
    },
    {
     "title": "Receive Level (dBmV) (QAM64)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "tc4400_downstream_receive_level_dbmv and on(channel) tc4400_downstream_modulation{modulation=~\"QAM64\"}",
       "legendFormat": "{{ `{{channel}}` }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Downstream Uncorrectable Codewords",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(tc4400_downstream_codewords_uncorrectable_total[5m]) > 0",
     "legendFormat": "CH{{ `{{channel}}` }}"
    }
   ]
  },
  {
   "title": "Upstream Channel Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(tc4400_upstream_center_frequency_hz) by (channel)"
    },
    {
     "expr": "avg(tc4400_upstream_locked) by (channel)"
    },
    {
     "expr": "avg(tc4400_upstream_bonded) by (channel)"
    },
    {
     "expr": "avg(tc4400_upstream_channel_type) by (channel,type)"
    },
    {
     "expr": "avg(tc4400_upstream_width_hz) by (channel)"
    },
    {
     "expr": "avg(tc4400_upstream_modulation) by (channel,modulation)"
    }
   ]
  },
  {
   "title": "Downstream Unerrored Codewords",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(tc4400_downstream_codewords_unerrored_total[5m]) > 0",
     "legendFormat": "CH{{ `{{channel}}` }}"
    }
   ]
  },
  {
   "title": "Downstream Corrected Codewords",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(tc4400_downstream_codewords_corrected_total[5m]) > 0",
     "legendFormat": "CH{{ `{{channel}}` }}"
    }
   ]
  },
  {
   "title": "Transmit Level (dBmV)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tc4400_upstream_transmit_level_dbmv",
     "legendFormat": "{{ `{{channel}}` }}"
    }
   ]
  }
 ]
}