---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-all-import
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 5
      activeDeadlineSeconds: 1200
      template:
        spec:
          containers:
            - name: sync-all-import-container
              image: curlimages/curl:8.18.0
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - 'curl --fail --silent --show-error -X POST "http://fints-actual-sync/api/imports/sync-all/"
          restartPolicy: Never