apiVersion: v1
kind: Pod
metadata:
  name: pgforward
  namespace: database
spec:
  containers:
    - name: pgforward
      image: alpine/socat
      command: ["socat", "-dd", "tcp4-listen:5432,fork,reuseaddr", "tcp4:database-cluster-rw.database.svc.cluster.local:5432"]
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"
      ports:
        - containerPort: 5432