app-template:
  controllers:
    main:
      strategy: RollingUpdate

      containers:
        main:
          image:
            repository: ghcr.io/antoncuranz/fints-actual-sync
            tag: latest
            pullPolicy: Always
          env:
            ACTUAL_API_URL: "http://actual.actual.svc.cluster.local:5007"
            ALLOWED_HOSTS: "*"
            CSRF_TRUSTED_ORIGINS: "https://fints.serverton.de"
            DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: database-fints-actual-sync-user
                  key: POSTGRES_URL
          envFrom:
            - secretRef:
                name: fints-actual-sync-secrets

  service:
    main:
      ports:
        http:
          port: 8000
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "lb1.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "fints.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: fints-actual-sync-tls-certificate
          hosts:
            - *host
