app-template:
  controllers:
    main:
      strategy: RollingUpdate

      containers:
        main:
          image:
            repository: ghcr.io/antoncuranz/fints-actual-sync
            tag: latest
            pullPolicy: Always
          env:
            LOG_LEVEL: "DEBUG"
            ACTUAL_API_URL: "http://actual.actual.svc.cluster.local:5007"
            ALLOWED_HOSTS: "*"
            CSRF_TRUSTED_ORIGINS: "https://fints.serverton.de"
            DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: database-fints-actual-sync-user
                  key: POSTGRES_URL
          envFrom:
            - secretRef:
                name: fints-actual-sync-secrets

  service:
    main:
      ports:
        http:
          port: 8000
  route:
    main:
      hostnames:
        - fints.serverton.de
      parentRefs:
        - name: envoy-gateway
          namespace: envoy-gateway
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - identifier: main
              port: 8000
