---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-secrets-crds
  namespace: secrets
spec:
  interval: 1m0s
  ref:
    tag: v0.20.4
  url: https://github.com/external-secrets/external-secrets
