app-template:
  controllers:
    main:
      strategy: RollingUpdate

      containers:
        main:
          image:
            repository: serjs/go-socks5-proxy
            tag: latest@sha256:6a7e47a21470ec4a3a8e722df8b94ae7bd5ac49e98eacfde945a3f6bf79ddf37
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

      pod:
        annotations:
          setGateway: "true"

  service:
    main:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: default
      ports:
        http:
          port: 1080
