apiVersion: v2
name: authentication
version: 0.0.0
dependencies:
  - name: keycloak
    version: 22.1.3
    repository: https://charts.bitnami.com/bitnami
  - name: oauth2-proxy
    version: 7.7.12
    repository: https://oauth2-proxy.github.io/manifests
