keycloak:
  image:
    repository: bitnamilegacy/keycloak
  production: true
  proxy: edge
  proxyHeaders: xforwarded
  resourcesPreset: "2xlarge"
  extraEnvVars:
    - name: "QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY"
      value: "true"
  ingress:
    enabled: false
  postgresql:
    enabled: false
  externalDatabase:
    host: database-cluster-rw.database.svc.cluster.local
    database: keycloak
    existingSecret: database-keycloak-user
    existingSecretUserKey: LOGIN
    existingSecretPasswordKey: PASSWORD
  initContainers:
    - name: theme-provider
      image: registry.gitlab.com/antoncuranz/keycloak-theme:latest
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /keywind/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme
  extraVolumeMounts:
    - name: theme
      mountPath: /opt/bitnami/keycloak/themes/keywind
  extraVolumes:
    - name: theme
      emptyDir: {}
  auth:
    adminPassword: "unused"
