app-template:
  controllers:
    main:
      pod:
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          fsGroup: 568
          fsGroupChangePolicy: OnRootMismatch

      containers:
        main:
          image:
            repository: ghcr.io/coder/code-server
            tag: 4.91.1
          args:
            - "--auth"
            - "none"
            - "--disable-telemetry"
            - "--user-data-dir"
            - "/config/.vscode"
            - "--extensions-dir"
            - "/config/.vscode"
            - "/data"
#          securityContext:
#            readOnlyRootFilesystem: true
#            allowPrivilegeEscalation: false
#            capabilities:
#              drop: ["ALL"]
#          resources:
#            limits:
#              cpu: "1000m"
#              memory: "4Gi"

  service:
    main:
      ports:
        http:
          port: 8080

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host "code.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *host

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
