app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/coder/code-server
            tag: 4.91.1
#          command: ["dumb-init", "/bin/bash", "-c"]
#          args: ["/home/linuxbrew/.linuxbrew/sbin/sshd -p 2222 || true; /usr/bin/code-server --auth none --disable-telemetry --user-data-dir /home/coder/.vscode --extensions-dir /home/coder/.vscode --bind-addr 0.0.0.0:8080 --port 8080 /home/coder"]
          securityContext:
#            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
#          resources:
#            limits:
#              cpu: "1000m"
#              memory: "4Gi"

  service:
    main:
      ports:
        http:
          port: 8080

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host "code.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *host

  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      globalMounts:
        - path: /home/coder