app-template:
  controllers:
    main:
      pod:
        hostNetwork: true

      containers:
        main:
          image:
            repository: ghcr.io/homebridge/homebridge
            tag: "2024-01-08"
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 750Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /login
                  port: 8581
                initialDelaySeconds: 30

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
      globalMounts:
        - path: /homebridge
      dataSourceRef:
        kind: ReplicationDestination
        apiGroup: volsync.backube
        name: homebridge-dst

  service:
    main:
      ports:
        http:
          port: 8581
        shelly:
          port: 8181

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "lb1.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "homebridge.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: homebridge-tls-certificate
          hosts:
            - *host
