app-template:
  controllers:
    main:
      pod:
        hostNetwork: true

      containers:
        main:
          image:
            repository: ghcr.io/homebridge/homebridge
            tag: "2024-01-08"
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 750Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /login
                  port: 8581
                initialDelaySeconds: 30

  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
      globalMounts:
        - path: /homebridge
      dataSourceRef:
        kind: ReplicationDestination
        apiGroup: volsync.backube
        name: homebridge-dst

  service:
    main:
      ports:
        http:
          port: 8581
        shelly:
          port: 8181

  route:
    main:
      hostnames:
        - homebridge.serverton.de
      parentRefs:
        - name: envoy-gateway
          namespace: envoy-gateway
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - identifier: main
              port: 8581
