kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-restricted
spec:
  podSelector: {}
  ingress:
    - from:
      # Only allow local ingress
      - ipBlock:
          cidr: 10.0.0.0/8
      - ipBlock:
          cidr: 172.16.0.0/12
      - ipBlock:
          cidr: 192.168.0.0/16
  egress:
    - to:
      # Only allow egress to K8S
      - ipBlock:
          cidr: 10.0.0.0/8
  policyTypes:
    - Ingress
    - Egress
