---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name outline-volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:{{ `{{ .S3_ENDPOINT }}` }}/outline"
        RESTIC_PASSWORD: "{{ `{{ .RESTIC_PASSWORD }}` }}"
        AWS_ACCESS_KEY_ID: "{{ `{{ .ACCESS_KEY_ID }}` }}"
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .ACCESS_SECRET_KEY }}` }}"
  dataFrom:
    - extract:
        key: b2-volsync
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: outline
spec:
  sourcePVC: outline-data
  trigger:
    schedule: "0 5 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: outline-volsync
    moverSecurityContext:
      runAsUser: 1001
      runAsGroup: 65533
      fsGroup: 65533
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: outline-dst
spec:
  trigger:
    manual: restore-once
  restic:
    repository: outline-volsync
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    capacity: 5Gi
    moverSecurityContext:
      runAsUser: 1001
      runAsGroup: 65533
      fsGroup: 65533