finance-backend:
  global:
    nameOverride: backend


  controllers:
    main:
      strategy: RollingUpdate

      pod:
        imagePullSecrets:
          - name: gitlab-token

      containers:
        main:
          image:
            repository: registry.gitlab.com/antoncuranz/financeq
            tag: dev
            pullPolicy: Always
          env:
            KEYCLOAK_REALM_URL: "https://keycloak.serverton.de/realms/serverton"
            KEYCLOAK_CLIENT_ID: "finance-backend"
            CORS_ALLOW_ORIGINS: "https://finance.serverton.de"
            CRON_ALERT_DELIVERY: "0 */15 * * * ?"
            CRON_TRANSACTION_VALIDATION: "0 0 */1 * * ?"
            POSTGRES_URL:
              valueFrom:
                secretKeyRef:
                  name: database-finance-user
                  key: POSTGRES_JDBC_URL
            POSTGRES_USER:
              valueFrom:
                secretKeyRef:
                  name: database-finance-user
                  key: LOGIN
            POSTGRES_PASSWD:
              valueFrom:
                secretKeyRef:
                  name: database-finance-user
                  key: PASSWORD
          envFrom:
            - secretRef:
                name: finance-secrets
  service:
    main:
      ports:
        http:
          port: 8080
        debug:
          port: 5005

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "lb1.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host "financeq.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: financeq-tls-certificate
          hosts:
            - *host

finance-frontend:
  global:
    nameOverride: frontend

  controllers:
    main:
      strategy: RollingUpdate

      pod:
        imagePullSecrets:
          - name: gitlab-token

      containers:
        main:
          image:
            repository: registry.gitlab.com/antoncuranz/financeionic
            tag: dev
            pullPolicy: Always
          env:
            KEYCLOAK_URL: "https://keycloak.serverton.de"
            KEYCLOAK_REALM: "serverton"
            KEYCLOAK_CLIENT_ID: "finance-frontend"
            BACKEND_URL: "https://financeq.serverton.de"

  service:
    main:
      ports:
        http:
          port: 80

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "lb1.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host "finance.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: finance-tls-certificate
          hosts:
            - *host
