---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kompass-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: kompass-secrets
  dataFrom:
    - extract:
        key: kompass