---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: epg-channels
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: epg-channels
    creationPolicy: Owner
  data:
    - secretKey: channels.xml
      remoteRef:
        key: epg
        property: tv.channels.xml
