---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-import
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: data-import-container
              image: curlimages/curl:8.11.1
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - 'curl -X POST "http://money-tracking-backend.money-tracking.svc.cluster.local/api/import" -v -H "X-Auth-Request-Preferred-Username: ant0n"'
          restartPolicy: Never