---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: teller-import
spec:
  schedule: "@daily"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: teller-import-container
              image: curlimages/curl:8.9.1
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - 'curl -X POST "http://money-tracking-backend.money-tracking.svc.cluster.local/api/import/1" -v'
          restartPolicy: Never