---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: storage
spec:
  interval: 1h
  chart:
    spec:
      chart: democratic-csi
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
      version: 0.15.1
  values:
    csiDriver:
      name: "org.democratic-csi.zfs-iscsi"

    storageClasses:
      - name: zfs-iscsi
        defaultClass: true
        reclaimPolicy: Retain
        volumeBindingMode: WaitForFirstConsumer
        parameters:
          fsType: ext4

    volumeSnapshotClasses:
      - name: zfs-iscsi
        annotations:
          snapshot.storage.kubernetes.io/is-default-class: "true"
        deletionPolicy: Delete
        parameters:
          detachedSnapshots: "false"

    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /var/iscsi
        iscsiDirHostPathType: ""

    driver:
      config:
        driver: zfs-generic-iscsi

        sshConnection:
          host: 192.168.1.2
          port: 22
          username: democratic-csi

        zfs:
          datasetParentName: zroot/k8s/iscsi
          detachedSnapshotsDatasetParentName: zroot/k8s/iscsi-snapshots
          iscsi:
            shareStrategy: "targetCli"
            shareStrategyTargetCli:
              sudoEnabled: true
              basename: "iqn.2026-08.nz.cura:homelab"
              tpg:
                attributes:
                  authentication: 0
                  generate_node_acls: 1
                  demo_mode_write_protect: 0
            targetPortal: "192.168.1.2:3260"
  valuesFrom:
    - kind: Secret
      name: democratic-csi
      valuesKey: Private-Key
      targetPath: driver.config.sshConnection.privateKey