app-template:
  controllers:
    main:
      strategy: RollingUpdate

      pod:
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
          fsGroupChangePolicy: OnRootMismatch

      containers:
        main:
          image:
            repository: actualbudget/actual-server
            tag: 26.4.0
          env:
            TZ: "Europe/Berlin"
            ACTUAL_PORT: "5006"
            ACTUAL_LOGIN_METHOD: "openid"
        rest:
          image:
            repository: ghcr.io/antoncuranz/actual-http-api
            tag: latest
            pullPolicy: Always
          env:
            ACTUAL_SERVER_URL: "http://actual.actual.svc.cluster.local:5006"
          envFrom:
            - secretRef:
                name: actual-secrets

  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4Gi
      dataSourceRef:
        kind: ReplicationDestination
        apiGroup: volsync.backube
        name: actual-dst

  service:
    main:
      ports:
        http:
          port: 5006
        rest:
          port: 5007

  route:
    main:
      hostnames:
        - "actual.serverton.de"
      parentRefs:
        - name: envoy-gateway
          namespace: envoy-gateway
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - identifier: main
              port: 5006
