---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
  namespace: secrets
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.secrets.svc.cluster.local:8080
      vaults:
        Cloudlab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-secret
            key: token
            namespace: secrets
