---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitcoind-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ant0n/bitcoin/bitcoind"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoind-data
  annotations:
    k8up.io/backup: 'false'
spec:
  volumeName: bitcoind-data-pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: electrs-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ant0n/bitcoin/electrs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: electrs-data
  annotations:
    k8up.io/backup: 'false'
spec:
  volumeName: electrs-data-pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
