---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bitcoind-secrets
spec:
  itemPath: "vaults/Kubernetes/items/bitcoind"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: tor-secrets
spec:
  itemPath: "vaults/Kubernetes/items/tor"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: fulcrum-secrets
spec:
  itemPath: "vaults/Kubernetes/items/fulcrum"
