apiVersion: v1
kind: Service
metadata:
  name: signal-cli
spec:
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: hermes
    app.kubernetes.io/name: signal-cli-rest-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
