---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
  namespace: secrets
spec:
  provider:
    fake:
      data:
        - key: cloudnative-pg
          value: '{"username":"postgres","password":"postgres"}'
        - key: b2-volsync
          value: '{"S3_ENDPOINT":"minio.local.test","RESTIC_PASSWORD":"local-restic-password","ACCESS_KEY_ID":"local-access-key","ACCESS_SECRET_KEY":"local-secret-key"}'
