---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
  namespace: secrets
spec:
  provider:
    fake:
      data:
        - key: kompass
          value: '{"APP_CONFIG":"window.APP_CONFIG = { apiBaseUrl: \"/api\" };","DATABASE_URL":"postgres://postgres:postgres@database-cluster-rw.database.svc.cluster.local:5432/postgres","JAZZ_WORKER_ACCOUNT":"local-secret","JAZZ_WORKER_SECRET":"local-secret","VAPID_SUBJECT":"local-secret","VAPID_PUBLIC_KEY":"local-secret","VAPID_PRIVATE_KEY":"local-secret"}'
        - key: metrics-basic-auth
          value: '{".htpasswd":"admin:$apr1$6G82PczQ$dAh4dboln54YIpTQAHqTr/"}'
        - key: Ext-Postgres Secrets
          value: '{"POSTGRES_HOST":"database-cluster-rw.database.svc.cluster.local:5432","POSTGRES_USER":"postgres","POSTGRES_PASS":"postgres","POSTGRES_URI_ARGS":"sslmode=disable","POSTGRES_CLOUD_PROVIDER":"local","POSTGRES_DEFAULT_DATABASE":"postgres"}'
        - key: cloudnative-pg
          value: '{"username":"postgres","password":"postgres"}'
        - key: b2-volsync
          value: '{"S3_ENDPOINT":"minio.local.test","RESTIC_PASSWORD":"local-restic-password","ACCESS_KEY_ID":"local-access-key","ACCESS_SECRET_KEY":"local-secret-key"}'
