apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-schedule
spec:
  schedule: "0 0 0 * * 0"
  backupOwnerReference: self
  cluster:
    name: database-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io