apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database-cluster
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.3.0
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  superuserSecret:
    name: postgres-secret
  enableSuperuserAccess: true
  backup:
    barmanObjectStore:
      destinationPath: s3://homelab-db/
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      serverName: database-cluster-c
      s3Credentials:
        accessKeyId:
          name: backblaze-db
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backblaze-db
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
    retentionPolicy: "90d"
  monitoring:
    enablePodMonitor: true