apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database-cluster
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17-0.3.0
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  superuserSecret:
    name: postgres-secret
  enableSuperuserAccess: true
  monitoring:
    enablePodMonitor: true
  plugins:
    - enabled: true
      name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: b2-object-store
        serverName: database-cluster-c
