apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database-cluster-2
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:15.7-v0.2.1
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  superuserSecret:
    name: postgres-secret
  enableSuperuserAccess: true
  bootstrap:
    recovery:
      backup:
        name: backup-schedule-20240714000000

  monitoring:
    enablePodMonitor: true