---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name postgres-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_PASS