---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name node-red-volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:{{ `{{ .S3_ENDPOINT }}` }}/node-red"
        RESTIC_PASSWORD: "{{ `{{ .RESTIC_PASSWORD }}` }}"
        AWS_ACCESS_KEY_ID: "{{ `{{ .ACCESS_KEY_ID }}` }}"
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .ACCESS_SECRET_KEY }}` }}"
  dataFrom:
    - extract:
        key: b2-volsync
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: node-red
spec:
  sourcePVC: iot-node-red-data
  trigger:
    schedule: "0 5 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: node-red-volsync
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      weekly: 4
      monthly: 3
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: node-red-dst
spec:
  trigger:
    manual: restore-once
  restic:
    repository: node-red-volsync
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    capacity: 250Mi
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568