backend:
  global:
    nameOverride: backend


  controllers:
    main:
      strategy: RollingUpdate

      containers:
        main:
          image:
            repository: ghcr.io/antoncuranz/money-tracking/backend
            tag: latest
            pullPolicy: Always
          env:
            ACTUAL_BASE_URL: "http://actual.actual.svc.cluster.local:5007"
            ACTUAL_CAT_FX_FEES: "ff41dcbd-5962-4b32-b3fe-ce9d63cf9c25"
            ACTUAL_CAT_GROCERIES: "ff259c77-c898-447e-a156-9ee299e09a32"
            ACTUAL_CAT_DINING: "c1e2f6d7-dd3c-4f66-a1b4-eb6916aba30c"
            POSTGRES_HOST:
              valueFrom:
                secretKeyRef:
                  name: database-money-tracking-user
                  key: HOST
            POSTGRES_DATABASE:
              valueFrom:
                secretKeyRef:
                  name: database-money-tracking-user
                  key: DATABASE_NAME
            POSTGRES_USER:
              valueFrom:
                secretKeyRef:
                  name: database-money-tracking-user
                  key: LOGIN
            POSTGRES_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: database-money-tracking-user
                  key: PASSWORD
          envFrom:
            - secretRef:
                name: money-tracking-secrets

  persistence:
    teller-certs:
      enabled: true
      type: secret
      name: money-tracking-secrets
      globalMounts:
        - path: /app/teller/certificate.pem
          subPath: TELLER_CERTIFICATE
        - path: /app/teller/private_key.pem
          subPath: TELLER_PRIVATE_KEY

  service:
    main:
      ports:
        http:
          port: 80

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "money-tracking.serverton.de"
          paths:
            - path: /api
              service:
                name: main
                port: http
      tls:
        - secretName: money-tracking-backend-tls-certificate
          hosts:
            - *host

frontend:
  global:
    nameOverride: frontend

  controllers:
    main:
      strategy: RollingUpdate

      containers:
        main:
          image:
            repository: ghcr.io/antoncuranz/money-tracking/frontend
            tag: latest
            pullPolicy: Always
          env:
            TELLER_APPLICATION_ID:
              valueFrom:
                secretKeyRef:
                  name: money-tracking-secrets
                  key: TELLER_APPLICATION_ID

  service:
    main:
      ports:
        http:
          port: 80

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      hosts:
        - host: &host "money-tracking.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: money-tracking-frontend-tls-certificate
          hosts:
            - *host
