app-template:
  controllers:
    main:
      strategy: RollingUpdate

      containers:
        main:
          image:
            repository: ghostfolio/ghostfolio
            tag: 2.255.0
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /api/v1/health
                  port: 3333
                initialDelaySeconds: 30
          env:
            REDIS_HOST: localhost
            DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: database-ghostfolio-user
                  key: POSTGRES_URL
          envFrom:
            - secretRef:
                name: ghostfolio-secret
        redis:
          image:
            repository: public.ecr.aws/docker/library/redis
            tag: 8.6.2

  service:
    main:
      ports:
        http:
          port: 3333

  route:
    main:
      hostnames:
        - ghostfolio.serverton.de
      parentRefs:
        - name: envoy-gateway
          namespace: envoy-gateway
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - identifier: main
              port: 3333
