firefly-iii:
  image:
    repository: fireflyiii/core
    tag: "version-6.1.19"

  persistence:
    enabled: true
    existingClaim: "fireflyiii-data"

  config:
    existingSecret: "database-fireflyiii-user"

    env:
      DB_CONNECTION: pgsql
      DB_PORT: "5432"
      DEFAULT_LANGUAGE: "en_US"
      DEFAULT_LOCALE: "equal"
      TZ: "Europe/Berlin"
      TRUSTED_PROXIES: "**"
      AUTHENTICATION_GUARD: "remote_user_guard"
      AUTHENTICATION_GUARD_HEADER: "HTTP_X_AUTH_REQUEST_EMAIL"

  podSecurityContext:
     fsGroup: 2000

#  securityContext:
#     capabilities:
#       drop:
#       - ALL
#     runAsNonRoot: true
#     runAsUser: 1000

  ingress:
    enabled: true
    className: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
      nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
    hosts:
      - &host "firefly.serverton.de"
    tls:
      - secretName: fireflyiii-tls-certificate
        hosts:
          - *host

importer:
  image:
    repository: fireflyiii/data-importer
    tag: "version-1.5.4"

  fireflyiii:
    url: "http://fireflyiii-firefly-iii.fireflyiii.svc.cluster.local:80"
    vanityUrl: "https://firefly.serverton.de"

    auth:
      existingSecret: "fireflyiii-importer-secret"
  config:
    existingSecret: "fireflyiii-importer-secret"

#  ingress:
#    enabled: true
#    className: nginx
#    annotations:
#      external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
#      cert-manager.io/cluster-issuer: letsencrypt-prod
#      nginx.ingress.kubernetes.io/auth-signin: https://oauth2.serverton.de/oauth2/start
#      nginx.ingress.kubernetes.io/auth-url: https://oauth2.serverton.de/oauth2/auth
#      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
#    hosts:
#      - &host "test.serverton.de"
#    tls:
#      - secretName: fireflyiii-importer-tls-certificate
#        hosts:
#          - *host
