app-template:
  controllers:
    main:
      strategy: RollingUpdate

#      pod:
#        securityContext:
#          runAsUser: 1001
#          runAsGroup: 1001
#          fsGroup: 1001
#          fsGroupChangePolicy: OnRootMismatch

      containers:
        main:
          image:
            repository: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder
            tag: latest
          env:
            LOGLEVEL: "error"
            TZ: "Europe/Berlin"
            READSB_DEVICE_TYPE: "rtlsdr"
            READSB_RTLSDR_DEVICE: "00000001"

            READSB_GAIN: "autogain"
            READSB_RX_LOCATION_ACCURACY: "2"
            READSB_STATS_RANGE: "true"

            ULTRAFEEDER_CONFIG: "mlathub,adsb-piaware,30105,beast_in;"

            READSB_FORWARD_MLAT_SBS: "true"

            UPDATE_TAR1090: "true"
            TAR1090_PLANECOUNTINTITLE: "true"
            TAR1090_ENABLE_AC_DB: "true"
            TAR1090_FLIGHTAWARELINKS: "true"
            TAR1090_SITESHOW: "true"
            TAR1090_RANGE_OUTLINE_COLORED_BY_ALTITUDE: "true"
            TAR1090_RANGE_OUTLINE_WIDTH: "2.0"
            TAR1090_RANGERINGSDISTANCES: "50,100,150,200"
            TAR1090_RANGERINGSCOLORS: "'#1A237E','#0D47A1','#42A5F5','#64B5F6'"
            TAR1090_USEROUTEAPI: "true"

            TAR1090_DEFAULTCENTERLAT:
              valueFrom:
                secretKeyRef:
                  name: adsb-secrets
                  key: READSB_LAT
            TAR1090_DEFAULTCENTERLON:
              valueFrom:
                secretKeyRef:
                  name: adsb-secrets
                  key: READSB_LON
          envFrom:
            - secretRef:
                name: adsb-secrets
          securityContext:
            privileged: true

    fr24:
      containers:
        fr24:
          image:
            repository: ghcr.io/sdr-enthusiasts/docker-flightradar24
            tag: latest
          env:
            BEASTHOST: "adsb"
            TZ: "Europe/Berlin"

            FR24KEY:
              valueFrom:
                secretKeyRef:
                  name: adsb-secrets
                  key: FR24_SHARING_KEY

    piaware:
      containers:
        piaware:
          image:
            repository: ghcr.io/sdr-enthusiasts/docker-piaware
            tag: latest
          env:
            BEASTHOST: "adsb"
            TZ: "Europe/Berlin"

            FEEDER_ID:
              valueFrom:
                secretKeyRef:
                  name: adsb-secrets
                  key: PIAWARE_FEEDER_ID

  persistence:
    rtlsdr:
      enabled: true
      type: hostPath
      hostPath: /dev/rtlsdr
    globe-history:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
      globalMounts:
        - path: /var/globe_history
    collectd:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi
      globalMounts:
        - path: /var/lib/collectd

  service:
    main:
      ports:
        http:
          port: 8080
        beast:
          port: 30005
    fr24:
      controller: fr24
      ports:
        http:
          port: 8754
    piaware:
      controller: piaware
      ports:
        http:
          port: 8080
        beast:
          port: 30105

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "ipv4.serverton.de"
      hosts:
        - host: &host "adsb.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: adsb-tls-certificate
          hosts:
            - *host
