---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: litellm-db
spec:
  database: litellm
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: litellm-user
spec:
  role: litellm
  database: litellm-db
  secretName: database
  privileges: OWNER
---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: open-webui-db
spec:
  database: openwebui
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: open-webui-user
spec:
  role: openwebui
  database: open-webui-db
  secretName: database
  privileges: OWNER