---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ai-secrets
spec:
  itemPath: "vaults/Kubernetes/items/ai-secrets"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: open-webui-secrets
spec:
  itemPath: "vaults/Kubernetes/items/open-webui"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: librechat-secrets
spec:
  itemPath: "vaults/Kubernetes/items/librechat"