minecraft:
  image:
    repository: itzg/minecraft-server
    tag: 2024.7.2

  minecraftServer:
    eula: "TRUE"
    type: "PAPER"
    motd: "§aMir ist langweilig, bespaße mich!§r"
    memory: 6G
    maxTickTime: -1 # autopause
    rcon:
      enabled: true
      existingSecret: minecraft-secret
      secretKey: rcon
    serviceType: LoadBalancer

  extraEnv:
    TZ: "Europe/Berlin"
    ENABLE_AUTOPAUSE: true
    AUTOPAUSE_TIMEOUT_EST: 900 # 15min
    AUTOPAUSE_TIMEOUT_INIT: 60 # 1min
    JVM_DD_OPTS: "disable.watchdog:true" # autopause
    SKIP_SUDO: true
    PAPER_CHANNEL: "experimental"

  serviceAnnotations:
    metallb.universe.tf/allow-shared-ip: default

  persistence:
    dataDir:
      enabled: true
      existingClaim: minecraft-data

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    runAsNonRoot: true

  # autopause
  securityContext:
    allowPrivilegeEscalation: true
    capabilities:
      add: [ "NET_RAW" ]
