app-template:
  controllers:
    main:
      strategy: RollingUpdate

      pod:
        securityContext:
          runAsUser: 911
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch

      containers:
        main:
          image:
            repository: crocodilestick/calibre-web-automated
            tag: latest
          env:
            CALIBRE_PORT: "8083"

  persistence:
    calibre-library:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4Gi

  service:
    main:
      ports:
        http:
          port: 8083

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "lb1.serverton.de"
      hosts:
        - host: &host "calibre.serverton.de"
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - secretName: calibre-tls-certificate
          hosts:
            - *host
