app-template:
  controllers:
    main:
      strategy: RollingUpdate

      containers:
        main:
          image:
            repository: crocodilestick/calibre-web-automated
            tag: latest
          env:
            CALIBRE_PORT: "8083"
            PUID: 1000
            PGID: 1000

  persistence:
    calibre-library:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4Gi

  service:
    main:
      ports:
        http:
          port: 8083

  route:
    main:
      hostnames:
        - "calibre.serverton.de"
      parentRefs:
        - name: envoy-gateway
          namespace: envoy-gateway
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - identifier: main
              port: 8083
