ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    config:
      annotations-risk-level: Critical
    service:
      externalTrafficPolicy: Cluster
      annotations:
        lbipam.cilium.io/ips: 192.168.1.10
        lbipam.cilium.io/sharing-key: default
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
