ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: default
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
